name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [production, development]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./spring-boot-server

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate package-lock.json
        run: npm install --package-lock-only
        working-directory: ./angular-15-client

      - name: Install dependencies
        run: npm ci
        working-directory: ./angular-15-client


      - name: Build Angular app
        run: npm run build -- --output-path=./dist/out --configuration ${{ matrix.configuration }}
        working-directory: ./angular-15-client

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/out/